// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package code.google.dsf.test.protobuf;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PbDTOOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 itemid = 1;
    boolean hasItemid();
    int getItemid();
    
    // optional string logid = 2;
    boolean hasLogid();
    String getLogid();
    
    // optional int32 userid = 3;
    boolean hasUserid();
    int getUserid();
    
    // optional string imei = 4;
    boolean hasImei();
    String getImei();
    
    // optional string sid = 5;
    boolean hasSid();
    String getSid();
    
    // optional double flowSize = 6;
    boolean hasFlowSize();
    double getFlowSize();
    
    // optional string beginTime = 7;
    boolean hasBeginTime();
    String getBeginTime();
    
    // optional string endTime = 8;
    boolean hasEndTime();
    String getEndTime();
    
    // optional int32 homecountry = 9;
    boolean hasHomecountry();
    int getHomecountry();
    
    // optional int32 visitcountry = 10;
    boolean hasVisitcountry();
    int getVisitcountry();
  }
  public static final class PbDTO extends
      com.google.protobuf.GeneratedMessage
      implements PbDTOOrBuilder {
    // Use PbDTO.newBuilder() to construct.
    private PbDTO(Builder builder) {
      super(builder);
    }
    private PbDTO(boolean noInit) {}
    
    private static final PbDTO defaultInstance;
    public static PbDTO getDefaultInstance() {
      return defaultInstance;
    }
    
    public PbDTO getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return code.google.dsf.test.protobuf.Test.internal_static_code_google_dsf_test_protobuf_PbDTO_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return code.google.dsf.test.protobuf.Test.internal_static_code_google_dsf_test_protobuf_PbDTO_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 itemid = 1;
    public static final int ITEMID_FIELD_NUMBER = 1;
    private int itemid_;
    public boolean hasItemid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getItemid() {
      return itemid_;
    }
    
    // optional string logid = 2;
    public static final int LOGID_FIELD_NUMBER = 2;
    private java.lang.Object logid_;
    public boolean hasLogid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getLogid() {
      java.lang.Object ref = logid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          logid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLogidBytes() {
      java.lang.Object ref = logid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        logid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 userid = 3;
    public static final int USERID_FIELD_NUMBER = 3;
    private int userid_;
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getUserid() {
      return userid_;
    }
    
    // optional string imei = 4;
    public static final int IMEI_FIELD_NUMBER = 4;
    private java.lang.Object imei_;
    public boolean hasImei() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getImei() {
      java.lang.Object ref = imei_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          imei_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getImeiBytes() {
      java.lang.Object ref = imei_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        imei_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string sid = 5;
    public static final int SID_FIELD_NUMBER = 5;
    private java.lang.Object sid_;
    public boolean hasSid() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getSid() {
      java.lang.Object ref = sid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSidBytes() {
      java.lang.Object ref = sid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional double flowSize = 6;
    public static final int FLOWSIZE_FIELD_NUMBER = 6;
    private double flowSize_;
    public boolean hasFlowSize() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public double getFlowSize() {
      return flowSize_;
    }
    
    // optional string beginTime = 7;
    public static final int BEGINTIME_FIELD_NUMBER = 7;
    private java.lang.Object beginTime_;
    public boolean hasBeginTime() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getBeginTime() {
      java.lang.Object ref = beginTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          beginTime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBeginTimeBytes() {
      java.lang.Object ref = beginTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        beginTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string endTime = 8;
    public static final int ENDTIME_FIELD_NUMBER = 8;
    private java.lang.Object endTime_;
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getEndTime() {
      java.lang.Object ref = endTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          endTime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEndTimeBytes() {
      java.lang.Object ref = endTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 homecountry = 9;
    public static final int HOMECOUNTRY_FIELD_NUMBER = 9;
    private int homecountry_;
    public boolean hasHomecountry() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public int getHomecountry() {
      return homecountry_;
    }
    
    // optional int32 visitcountry = 10;
    public static final int VISITCOUNTRY_FIELD_NUMBER = 10;
    private int visitcountry_;
    public boolean hasVisitcountry() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public int getVisitcountry() {
      return visitcountry_;
    }
    
    private void initFields() {
      itemid_ = 0;
      logid_ = "";
      userid_ = 0;
      imei_ = "";
      sid_ = "";
      flowSize_ = 0D;
      beginTime_ = "";
      endTime_ = "";
      homecountry_ = 0;
      visitcountry_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasItemid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, itemid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLogidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, userid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getImeiBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSidBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, flowSize_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getBeginTimeBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getEndTimeBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, homecountry_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, visitcountry_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, itemid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLogidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, userid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getImeiBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSidBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, flowSize_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getBeginTimeBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getEndTimeBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, homecountry_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, visitcountry_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static code.google.dsf.test.protobuf.Test.PbDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static code.google.dsf.test.protobuf.Test.PbDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static code.google.dsf.test.protobuf.Test.PbDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static code.google.dsf.test.protobuf.Test.PbDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static code.google.dsf.test.protobuf.Test.PbDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static code.google.dsf.test.protobuf.Test.PbDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static code.google.dsf.test.protobuf.Test.PbDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static code.google.dsf.test.protobuf.Test.PbDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static code.google.dsf.test.protobuf.Test.PbDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static code.google.dsf.test.protobuf.Test.PbDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(code.google.dsf.test.protobuf.Test.PbDTO prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements code.google.dsf.test.protobuf.Test.PbDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return code.google.dsf.test.protobuf.Test.internal_static_code_google_dsf_test_protobuf_PbDTO_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return code.google.dsf.test.protobuf.Test.internal_static_code_google_dsf_test_protobuf_PbDTO_fieldAccessorTable;
      }
      
      // Construct using code.google.dsf.test.protobuf.Test.PbDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        itemid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        logid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        userid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        imei_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        sid_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        flowSize_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        beginTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        endTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        homecountry_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        visitcountry_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return code.google.dsf.test.protobuf.Test.PbDTO.getDescriptor();
      }
      
      public code.google.dsf.test.protobuf.Test.PbDTO getDefaultInstanceForType() {
        return code.google.dsf.test.protobuf.Test.PbDTO.getDefaultInstance();
      }
      
      public code.google.dsf.test.protobuf.Test.PbDTO build() {
        code.google.dsf.test.protobuf.Test.PbDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private code.google.dsf.test.protobuf.Test.PbDTO buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        code.google.dsf.test.protobuf.Test.PbDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public code.google.dsf.test.protobuf.Test.PbDTO buildPartial() {
        code.google.dsf.test.protobuf.Test.PbDTO result = new code.google.dsf.test.protobuf.Test.PbDTO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.itemid_ = itemid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.logid_ = logid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userid_ = userid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.imei_ = imei_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sid_ = sid_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.flowSize_ = flowSize_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.beginTime_ = beginTime_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.endTime_ = endTime_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.homecountry_ = homecountry_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.visitcountry_ = visitcountry_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof code.google.dsf.test.protobuf.Test.PbDTO) {
          return mergeFrom((code.google.dsf.test.protobuf.Test.PbDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(code.google.dsf.test.protobuf.Test.PbDTO other) {
        if (other == code.google.dsf.test.protobuf.Test.PbDTO.getDefaultInstance()) return this;
        if (other.hasItemid()) {
          setItemid(other.getItemid());
        }
        if (other.hasLogid()) {
          setLogid(other.getLogid());
        }
        if (other.hasUserid()) {
          setUserid(other.getUserid());
        }
        if (other.hasImei()) {
          setImei(other.getImei());
        }
        if (other.hasSid()) {
          setSid(other.getSid());
        }
        if (other.hasFlowSize()) {
          setFlowSize(other.getFlowSize());
        }
        if (other.hasBeginTime()) {
          setBeginTime(other.getBeginTime());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        if (other.hasHomecountry()) {
          setHomecountry(other.getHomecountry());
        }
        if (other.hasVisitcountry()) {
          setVisitcountry(other.getVisitcountry());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasItemid()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              itemid_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              logid_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              userid_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              imei_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              sid_ = input.readBytes();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              flowSize_ = input.readDouble();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              beginTime_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              endTime_ = input.readBytes();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              homecountry_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              visitcountry_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 itemid = 1;
      private int itemid_ ;
      public boolean hasItemid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getItemid() {
        return itemid_;
      }
      public Builder setItemid(int value) {
        bitField0_ |= 0x00000001;
        itemid_ = value;
        onChanged();
        return this;
      }
      public Builder clearItemid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        itemid_ = 0;
        onChanged();
        return this;
      }
      
      // optional string logid = 2;
      private java.lang.Object logid_ = "";
      public boolean hasLogid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getLogid() {
        java.lang.Object ref = logid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          logid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLogid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        logid_ = value;
        onChanged();
        return this;
      }
      public Builder clearLogid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        logid_ = getDefaultInstance().getLogid();
        onChanged();
        return this;
      }
      void setLogid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        logid_ = value;
        onChanged();
      }
      
      // optional int32 userid = 3;
      private int userid_ ;
      public boolean hasUserid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getUserid() {
        return userid_;
      }
      public Builder setUserid(int value) {
        bitField0_ |= 0x00000004;
        userid_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userid_ = 0;
        onChanged();
        return this;
      }
      
      // optional string imei = 4;
      private java.lang.Object imei_ = "";
      public boolean hasImei() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getImei() {
        java.lang.Object ref = imei_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          imei_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setImei(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        imei_ = value;
        onChanged();
        return this;
      }
      public Builder clearImei() {
        bitField0_ = (bitField0_ & ~0x00000008);
        imei_ = getDefaultInstance().getImei();
        onChanged();
        return this;
      }
      void setImei(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        imei_ = value;
        onChanged();
      }
      
      // optional string sid = 5;
      private java.lang.Object sid_ = "";
      public boolean hasSid() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getSid() {
        java.lang.Object ref = sid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sid_ = value;
        onChanged();
        return this;
      }
      public Builder clearSid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sid_ = getDefaultInstance().getSid();
        onChanged();
        return this;
      }
      void setSid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        sid_ = value;
        onChanged();
      }
      
      // optional double flowSize = 6;
      private double flowSize_ ;
      public boolean hasFlowSize() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public double getFlowSize() {
        return flowSize_;
      }
      public Builder setFlowSize(double value) {
        bitField0_ |= 0x00000020;
        flowSize_ = value;
        onChanged();
        return this;
      }
      public Builder clearFlowSize() {
        bitField0_ = (bitField0_ & ~0x00000020);
        flowSize_ = 0D;
        onChanged();
        return this;
      }
      
      // optional string beginTime = 7;
      private java.lang.Object beginTime_ = "";
      public boolean hasBeginTime() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getBeginTime() {
        java.lang.Object ref = beginTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          beginTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBeginTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        beginTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearBeginTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        beginTime_ = getDefaultInstance().getBeginTime();
        onChanged();
        return this;
      }
      void setBeginTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        beginTime_ = value;
        onChanged();
      }
      
      // optional string endTime = 8;
      private java.lang.Object endTime_ = "";
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getEndTime() {
        java.lang.Object ref = endTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          endTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEndTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        endTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000080);
        endTime_ = getDefaultInstance().getEndTime();
        onChanged();
        return this;
      }
      void setEndTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        endTime_ = value;
        onChanged();
      }
      
      // optional int32 homecountry = 9;
      private int homecountry_ ;
      public boolean hasHomecountry() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public int getHomecountry() {
        return homecountry_;
      }
      public Builder setHomecountry(int value) {
        bitField0_ |= 0x00000100;
        homecountry_ = value;
        onChanged();
        return this;
      }
      public Builder clearHomecountry() {
        bitField0_ = (bitField0_ & ~0x00000100);
        homecountry_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 visitcountry = 10;
      private int visitcountry_ ;
      public boolean hasVisitcountry() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public int getVisitcountry() {
        return visitcountry_;
      }
      public Builder setVisitcountry(int value) {
        bitField0_ |= 0x00000200;
        visitcountry_ = value;
        onChanged();
        return this;
      }
      public Builder clearVisitcountry() {
        bitField0_ = (bitField0_ & ~0x00000200);
        visitcountry_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:code.google.dsf.test.protobuf.PbDTO)
    }
    
    static {
      defaultInstance = new PbDTO(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:code.google.dsf.test.protobuf.PbDTO)
  }
  
  public interface PbListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .code.google.dsf.test.protobuf.PbDTO dto = 1;
    java.util.List<code.google.dsf.test.protobuf.Test.PbDTO> 
        getDtoList();
    code.google.dsf.test.protobuf.Test.PbDTO getDto(int index);
    int getDtoCount();
    java.util.List<? extends code.google.dsf.test.protobuf.Test.PbDTOOrBuilder> 
        getDtoOrBuilderList();
    code.google.dsf.test.protobuf.Test.PbDTOOrBuilder getDtoOrBuilder(
        int index);
  }
  public static final class PbList extends
      com.google.protobuf.GeneratedMessage
      implements PbListOrBuilder {
    // Use PbList.newBuilder() to construct.
    private PbList(Builder builder) {
      super(builder);
    }
    private PbList(boolean noInit) {}
    
    private static final PbList defaultInstance;
    public static PbList getDefaultInstance() {
      return defaultInstance;
    }
    
    public PbList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return code.google.dsf.test.protobuf.Test.internal_static_code_google_dsf_test_protobuf_PbList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return code.google.dsf.test.protobuf.Test.internal_static_code_google_dsf_test_protobuf_PbList_fieldAccessorTable;
    }
    
    // repeated .code.google.dsf.test.protobuf.PbDTO dto = 1;
    public static final int DTO_FIELD_NUMBER = 1;
    private java.util.List<code.google.dsf.test.protobuf.Test.PbDTO> dto_;
    public java.util.List<code.google.dsf.test.protobuf.Test.PbDTO> getDtoList() {
      return dto_;
    }
    public java.util.List<? extends code.google.dsf.test.protobuf.Test.PbDTOOrBuilder> 
        getDtoOrBuilderList() {
      return dto_;
    }
    public int getDtoCount() {
      return dto_.size();
    }
    public code.google.dsf.test.protobuf.Test.PbDTO getDto(int index) {
      return dto_.get(index);
    }
    public code.google.dsf.test.protobuf.Test.PbDTOOrBuilder getDtoOrBuilder(
        int index) {
      return dto_.get(index);
    }
    
    private void initFields() {
      dto_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getDtoCount(); i++) {
        if (!getDto(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < dto_.size(); i++) {
        output.writeMessage(1, dto_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < dto_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, dto_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static code.google.dsf.test.protobuf.Test.PbList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static code.google.dsf.test.protobuf.Test.PbList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static code.google.dsf.test.protobuf.Test.PbList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static code.google.dsf.test.protobuf.Test.PbList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static code.google.dsf.test.protobuf.Test.PbList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static code.google.dsf.test.protobuf.Test.PbList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static code.google.dsf.test.protobuf.Test.PbList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static code.google.dsf.test.protobuf.Test.PbList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static code.google.dsf.test.protobuf.Test.PbList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static code.google.dsf.test.protobuf.Test.PbList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(code.google.dsf.test.protobuf.Test.PbList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements code.google.dsf.test.protobuf.Test.PbListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return code.google.dsf.test.protobuf.Test.internal_static_code_google_dsf_test_protobuf_PbList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return code.google.dsf.test.protobuf.Test.internal_static_code_google_dsf_test_protobuf_PbList_fieldAccessorTable;
      }
      
      // Construct using code.google.dsf.test.protobuf.Test.PbList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDtoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (dtoBuilder_ == null) {
          dto_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dtoBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return code.google.dsf.test.protobuf.Test.PbList.getDescriptor();
      }
      
      public code.google.dsf.test.protobuf.Test.PbList getDefaultInstanceForType() {
        return code.google.dsf.test.protobuf.Test.PbList.getDefaultInstance();
      }
      
      public code.google.dsf.test.protobuf.Test.PbList build() {
        code.google.dsf.test.protobuf.Test.PbList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private code.google.dsf.test.protobuf.Test.PbList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        code.google.dsf.test.protobuf.Test.PbList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public code.google.dsf.test.protobuf.Test.PbList buildPartial() {
        code.google.dsf.test.protobuf.Test.PbList result = new code.google.dsf.test.protobuf.Test.PbList(this);
        int from_bitField0_ = bitField0_;
        if (dtoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            dto_ = java.util.Collections.unmodifiableList(dto_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.dto_ = dto_;
        } else {
          result.dto_ = dtoBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof code.google.dsf.test.protobuf.Test.PbList) {
          return mergeFrom((code.google.dsf.test.protobuf.Test.PbList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(code.google.dsf.test.protobuf.Test.PbList other) {
        if (other == code.google.dsf.test.protobuf.Test.PbList.getDefaultInstance()) return this;
        if (dtoBuilder_ == null) {
          if (!other.dto_.isEmpty()) {
            if (dto_.isEmpty()) {
              dto_ = other.dto_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDtoIsMutable();
              dto_.addAll(other.dto_);
            }
            onChanged();
          }
        } else {
          if (!other.dto_.isEmpty()) {
            if (dtoBuilder_.isEmpty()) {
              dtoBuilder_.dispose();
              dtoBuilder_ = null;
              dto_ = other.dto_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dtoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDtoFieldBuilder() : null;
            } else {
              dtoBuilder_.addAllMessages(other.dto_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getDtoCount(); i++) {
          if (!getDto(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              code.google.dsf.test.protobuf.Test.PbDTO.Builder subBuilder = code.google.dsf.test.protobuf.Test.PbDTO.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addDto(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .code.google.dsf.test.protobuf.PbDTO dto = 1;
      private java.util.List<code.google.dsf.test.protobuf.Test.PbDTO> dto_ =
        java.util.Collections.emptyList();
      private void ensureDtoIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          dto_ = new java.util.ArrayList<code.google.dsf.test.protobuf.Test.PbDTO>(dto_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          code.google.dsf.test.protobuf.Test.PbDTO, code.google.dsf.test.protobuf.Test.PbDTO.Builder, code.google.dsf.test.protobuf.Test.PbDTOOrBuilder> dtoBuilder_;
      
      public java.util.List<code.google.dsf.test.protobuf.Test.PbDTO> getDtoList() {
        if (dtoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dto_);
        } else {
          return dtoBuilder_.getMessageList();
        }
      }
      public int getDtoCount() {
        if (dtoBuilder_ == null) {
          return dto_.size();
        } else {
          return dtoBuilder_.getCount();
        }
      }
      public code.google.dsf.test.protobuf.Test.PbDTO getDto(int index) {
        if (dtoBuilder_ == null) {
          return dto_.get(index);
        } else {
          return dtoBuilder_.getMessage(index);
        }
      }
      public Builder setDto(
          int index, code.google.dsf.test.protobuf.Test.PbDTO value) {
        if (dtoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDtoIsMutable();
          dto_.set(index, value);
          onChanged();
        } else {
          dtoBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setDto(
          int index, code.google.dsf.test.protobuf.Test.PbDTO.Builder builderForValue) {
        if (dtoBuilder_ == null) {
          ensureDtoIsMutable();
          dto_.set(index, builderForValue.build());
          onChanged();
        } else {
          dtoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addDto(code.google.dsf.test.protobuf.Test.PbDTO value) {
        if (dtoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDtoIsMutable();
          dto_.add(value);
          onChanged();
        } else {
          dtoBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addDto(
          int index, code.google.dsf.test.protobuf.Test.PbDTO value) {
        if (dtoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDtoIsMutable();
          dto_.add(index, value);
          onChanged();
        } else {
          dtoBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addDto(
          code.google.dsf.test.protobuf.Test.PbDTO.Builder builderForValue) {
        if (dtoBuilder_ == null) {
          ensureDtoIsMutable();
          dto_.add(builderForValue.build());
          onChanged();
        } else {
          dtoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addDto(
          int index, code.google.dsf.test.protobuf.Test.PbDTO.Builder builderForValue) {
        if (dtoBuilder_ == null) {
          ensureDtoIsMutable();
          dto_.add(index, builderForValue.build());
          onChanged();
        } else {
          dtoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllDto(
          java.lang.Iterable<? extends code.google.dsf.test.protobuf.Test.PbDTO> values) {
        if (dtoBuilder_ == null) {
          ensureDtoIsMutable();
          super.addAll(values, dto_);
          onChanged();
        } else {
          dtoBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearDto() {
        if (dtoBuilder_ == null) {
          dto_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dtoBuilder_.clear();
        }
        return this;
      }
      public Builder removeDto(int index) {
        if (dtoBuilder_ == null) {
          ensureDtoIsMutable();
          dto_.remove(index);
          onChanged();
        } else {
          dtoBuilder_.remove(index);
        }
        return this;
      }
      public code.google.dsf.test.protobuf.Test.PbDTO.Builder getDtoBuilder(
          int index) {
        return getDtoFieldBuilder().getBuilder(index);
      }
      public code.google.dsf.test.protobuf.Test.PbDTOOrBuilder getDtoOrBuilder(
          int index) {
        if (dtoBuilder_ == null) {
          return dto_.get(index);  } else {
          return dtoBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends code.google.dsf.test.protobuf.Test.PbDTOOrBuilder> 
           getDtoOrBuilderList() {
        if (dtoBuilder_ != null) {
          return dtoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dto_);
        }
      }
      public code.google.dsf.test.protobuf.Test.PbDTO.Builder addDtoBuilder() {
        return getDtoFieldBuilder().addBuilder(
            code.google.dsf.test.protobuf.Test.PbDTO.getDefaultInstance());
      }
      public code.google.dsf.test.protobuf.Test.PbDTO.Builder addDtoBuilder(
          int index) {
        return getDtoFieldBuilder().addBuilder(
            index, code.google.dsf.test.protobuf.Test.PbDTO.getDefaultInstance());
      }
      public java.util.List<code.google.dsf.test.protobuf.Test.PbDTO.Builder> 
           getDtoBuilderList() {
        return getDtoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          code.google.dsf.test.protobuf.Test.PbDTO, code.google.dsf.test.protobuf.Test.PbDTO.Builder, code.google.dsf.test.protobuf.Test.PbDTOOrBuilder> 
          getDtoFieldBuilder() {
        if (dtoBuilder_ == null) {
          dtoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              code.google.dsf.test.protobuf.Test.PbDTO, code.google.dsf.test.protobuf.Test.PbDTO.Builder, code.google.dsf.test.protobuf.Test.PbDTOOrBuilder>(
                  dto_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          dto_ = null;
        }
        return dtoBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:code.google.dsf.test.protobuf.PbList)
    }
    
    static {
      defaultInstance = new PbList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:code.google.dsf.test.protobuf.PbList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_code_google_dsf_test_protobuf_PbDTO_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_code_google_dsf_test_protobuf_PbDTO_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_code_google_dsf_test_protobuf_PbList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_code_google_dsf_test_protobuf_PbList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\035code.google.dsf.test.proto" +
      "buf\"\262\001\n\005PbDTO\022\016\n\006itemid\030\001 \002(\005\022\r\n\005logid\030\002" +
      " \001(\t\022\016\n\006userid\030\003 \001(\005\022\014\n\004imei\030\004 \001(\t\022\013\n\003si" +
      "d\030\005 \001(\t\022\020\n\010flowSize\030\006 \001(\001\022\021\n\tbeginTime\030\007" +
      " \001(\t\022\017\n\007endTime\030\010 \001(\t\022\023\n\013homecountry\030\t \001" +
      "(\005\022\024\n\014visitcountry\030\n \001(\005\";\n\006PbList\0221\n\003dt" +
      "o\030\001 \003(\0132$.code.google.dsf.test.protobuf." +
      "PbDTO"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_code_google_dsf_test_protobuf_PbDTO_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_code_google_dsf_test_protobuf_PbDTO_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_code_google_dsf_test_protobuf_PbDTO_descriptor,
              new java.lang.String[] { "Itemid", "Logid", "Userid", "Imei", "Sid", "FlowSize", "BeginTime", "EndTime", "Homecountry", "Visitcountry", },
              code.google.dsf.test.protobuf.Test.PbDTO.class,
              code.google.dsf.test.protobuf.Test.PbDTO.Builder.class);
          internal_static_code_google_dsf_test_protobuf_PbList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_code_google_dsf_test_protobuf_PbList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_code_google_dsf_test_protobuf_PbList_descriptor,
              new java.lang.String[] { "Dto", },
              code.google.dsf.test.protobuf.Test.PbList.class,
              code.google.dsf.test.protobuf.Test.PbList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
